//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VeClientEntities : DbContext
    {
        public VeClientEntities()
            : base("name=VeClientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstCivil> EstCivils { get; set; }
        public virtual DbSet<SeVeClie> SeVeClies { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int sp_UpdateSeVeClieById(string idClie, string cedula, string nombre, string apellido, string genero, Nullable<System.DateTime> fecha_nac, Nullable<int> id_estado_civil, Nullable<System.DateTime> updated_at)
        {
            var idClieParameter = idClie != null ?
                new ObjectParameter("IdClie", idClie) :
                new ObjectParameter("IdClie", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_nacParameter = fecha_nac.HasValue ?
                new ObjectParameter("Fecha_nac", fecha_nac) :
                new ObjectParameter("Fecha_nac", typeof(System.DateTime));
    
            var id_estado_civilParameter = id_estado_civil.HasValue ?
                new ObjectParameter("Id_estado_civil", id_estado_civil) :
                new ObjectParameter("Id_estado_civil", typeof(int));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("Updated_at", updated_at) :
                new ObjectParameter("Updated_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSeVeClieById", idClieParameter, cedulaParameter, nombreParameter, apellidoParameter, generoParameter, fecha_nacParameter, id_estado_civilParameter, updated_atParameter);
        }
    
        public virtual ObjectResult<sp_GetAllSeVeClie_Result> sp_GetAllSeVeClie(Nullable<int> pageSize, Nullable<int> pageNum, string orderField, string orderDir, string filterValue)
        {
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageNumParameter = pageNum.HasValue ?
                new ObjectParameter("PageNum", pageNum) :
                new ObjectParameter("PageNum", typeof(int));
    
            var orderFieldParameter = orderField != null ?
                new ObjectParameter("OrderField", orderField) :
                new ObjectParameter("OrderField", typeof(string));
    
            var orderDirParameter = orderDir != null ?
                new ObjectParameter("OrderDir", orderDir) :
                new ObjectParameter("OrderDir", typeof(string));
    
            var filterValueParameter = filterValue != null ?
                new ObjectParameter("FilterValue", filterValue) :
                new ObjectParameter("FilterValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllSeVeClie_Result>("sp_GetAllSeVeClie", pageSizeParameter, pageNumParameter, orderFieldParameter, orderDirParameter, filterValueParameter);
        }
    
        public virtual ObjectResult<sp_GetSeVeClieById_Result> sp_GetSeVeClieById(string idClie)
        {
            var idClieParameter = idClie != null ?
                new ObjectParameter("IdClie", idClie) :
                new ObjectParameter("IdClie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSeVeClieById_Result>("sp_GetSeVeClieById", idClieParameter);
        }
    }
}
